-- Replace current questions with AI Avenue quiz questions
-- Migration: 0005_ai_avenue_questions.sql

-- Clear existing questions
DELETE FROM questions;

-- Insert AI Avenue quiz questions
INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
('What does RAG stand for in AI?', 'Reasoning Against Generics', 'Retrieval-Augmented Generation', 'Recursive Algorithm Grid', 'Robots Against Greg', 1, 'RAG stands for Retrieval-Augmented Generation, a technique that combines the power of large language models with the ability to retrieve relevant information from external knowledge sources to generate more accurate and up-to-date responses.'),

('What does a Large Language Model (LLM) actually do?', 'Translates languages in real time', 'Generates the next most likely word based on input text', 'Reasons critically through complex problems in prompts', 'Controls Yorick''s trivia show in real time', 1, 'Large Language Models fundamentally work by predicting the next most likely word (or token) based on the input text they receive. While they can appear to reason or translate, their core mechanism is sophisticated pattern matching and statistical prediction of text sequences.'),

('Which of these best describes a "system prompt"?', 'The AI''s morning affirmation', 'A safety constraint baked into model architecture', 'An initial instruction that guides the model''s tone and behavior', 'A code that unlocks Yorick''s rebellious side', 2, 'A system prompt is an initial instruction given to an AI model that sets the context, tone, role, and behavior guidelines for the conversation. It''s like giving the AI a job description and personality guide before it starts responding to user inputs.'),

('What does "multimodal AI" refer to?', 'AI that wears multiple outfits during a conversation', 'AI that can process and generate text, images, audio, or video', 'AI that switches between reasoning models', 'AI that connects to both Wi-Fi and Bluetooth', 1, 'Multimodal AI refers to artificial intelligence systems that can understand, process, and generate content across multiple types of data or "modalities" - such as text, images, audio, and video. Examples include models that can analyze images and describe them in text, or generate images from text descriptions.'),

('Which of these AI applications uses "diffusion models"?', 'Voice cloning', 'Generative image creation', 'AI-powered deodorant', 'Real-time trivia judging', 1, 'Diffusion models are primarily used for generative image creation. They work by learning to gradually remove noise from images during training, then reversing this process to generate new images from pure noise. Popular examples include DALL-E, Midjourney, and Stable Diffusion.'),

('What differentiates an "agent" from a basic chatbot?', 'Agents can plan, use tools, and act autonomously', 'Agents wear suits and work for the government', 'Chatbots work solo; agents only work in duos', 'Agents require fine-tuning; chatbots just wing it', 0, 'AI agents are distinguished from basic chatbots by their ability to plan multi-step actions, use external tools and APIs, and act autonomously to achieve goals. While chatbots typically just respond to individual messages, agents can break down complex tasks, make decisions, and take actions in the real world.'),

('Which of the following is a valid solution to keep LLMs up to date with recent events?', 'Use prompt chaining to re-teach the model facts about current events', 'Regularly retrain the model by appending new data to the end of its original dataset', 'Integrating real-time search or retrieval tools like RAG', 'Setting its temperature to 0.0 so it chills out', 2, 'The most practical solution to keep LLMs current is integrating real-time search or retrieval tools like RAG (Retrieval-Augmented Generation). This allows the model to access up-to-date information from external sources without requiring expensive retraining of the entire model.'),

('In computer vision, what is semantic segmentation?', 'Drawing boxes around known objects in an image', 'Splitting text into different meanings using sentiment detection', 'Labeling every pixel in an image by the object it belongs to', 'Breaking down prompts into polite and impolite parts', 2, 'Semantic segmentation is a computer vision technique that assigns a class label to every pixel in an image, essentially creating a detailed map of what object or category each pixel belongs to. This is more precise than object detection (which draws bounding boxes) as it provides pixel-perfect boundaries.'),

('Which of these is an actual AI alignment strategy?', 'Reinforcement Learning from Human Feedback (RLHF)', 'Prompt Positivity Balancing (PPB)', 'Predictive Compliance Tuning (PCT)', 'Please Don''t Be Evil (PDBE)', 0, 'Reinforcement Learning from Human Feedback (RLHF) is a real AI alignment technique used to train models to behave according to human preferences. It involves having humans rate model outputs, then using those ratings to fine-tune the model to produce responses that humans find more helpful, harmless, and honest.'),

('How do you really get better at using AI tools?', 'Study computer science theory, learn languages, memorize code', 'You can''t, some skills are just in-built or not', 'Just wait until GPT-8 does it all for you', 'Experiment, build small projects, and watch AI Avenue', 3, 'The best way to improve with AI tools is through hands-on practice: experimenting with different prompts, building small projects to solve real problems, and learning from resources like AI Avenue. While technical knowledge helps, practical experience and understanding how to communicate effectively with AI systems is most important.');